FROM php:8.3-fpm

# Gerekli paketler
RUN apt-get update && apt-get install -y \
    git curl zip unzip \
    && docker-php-ext-install pdo_mysql

WORKDIR /var/www/html

# Composer kur
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

CMD php artisan serve --host=0.0.0.0 --port=8000
